services:
    palmtree_canonical_url.url_generator:
        class: Palmtree\CanonicalUrlBundle\Service\CanonicalUrlGenerator
        arguments: ['@router']
    palmtree_canonical_url.request_listener:
        class: Palmtree\CanonicalUrlBundle\EventListener\RequestListener
        arguments: ['@palmtree_canonical_url.url_generator']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    palmtree_canonical_url.exception_listener:
        class: Palmtree\CanonicalUrlBundle\EventListener\ExceptionListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    palmtree_canonical_url.twig_extension:
        class: Palmtree\CanonicalUrlBundle\Twig\Extension\CanonicalLinkExtension
        arguments: ['@palmtree_canonical_url.url_generator', '@request_stack']
        public: false
        tags:
            - { name: twig.extension }
