language: php

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 7.1
      env: PHPSNIFF=1 PHPLINT=1 PHPUNIT=1
    - php: 7.0
      env: PHPLINT=1
    - php: 5.5
      env: PHPLINT=1
    - php: hhvm


cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
- composer install --no-interaction --prefer-dist

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPUNIT" == "1" ]]; then vendor/bin/phpunit -v --coverage-text; fi
- if [[ "$PHPSNIFF" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 vendor/bin/phpcs --standard="PSR2" -v; fi
